branch-defaults:
  main:
    environment: Dockerreact-env
version: 2.1
global:
  application_name: docker-react
  default_ec2_keyname: XXXXXX
  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: ap-northeast-1
  sc: git