version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18-alpine
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: docker build -t arpitgarg/learn-react-docker

workflows:
  aws_deploy:
    jobs:
      - test